### ISSUE TITLE
Behat 3.1.0 compatibility

### ISSUE THREAD

**Issue by nicrodgers** [ciaranmcnulty/behat-stepthroughextension#3]
Since updating to Behat 3.1.0, when trying to run Behat with the stepthroughextension enabled, we get the following error:
[ReflectionException]
  Class Behat\Behat\Output\Printer\ConsoleOutputPrinter does not exist

Are there any plans to update this really useful extension to support 3.1.0?
thanks

**Comment by ciaranmcnulty** [comment]
This is an upstream BC break in Behat https://github.com/Behat/Behat/commit/d4c04f146309294ab8a731eae0786b7b438750eb

**Comment by ciaranmcnulty** [comment]
This will work in the next release
